baseURL = 'https://jaypatel-31.github.io/tech-blog/'
languageCode = 'en-us'
# title = 'Jay Writes'
theme = "congo"
# config/_default/languages.en.toml

title = "My awesome website"

[author]
name = "Jay Patel"
image = "wp7460286.jpg"
headline = "A generally awesome human"
bio = "A little bit about me"
links = [
  { twitter = "https://twitter.com/username" }
]
